const data = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://www.seriouseats.com/thmb/AVdCUACjl50RScwPNVRjVq-Nb4M=/1500x1125/filters:fill(auto,1)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2017__07__20170728-sunny-side-up-eggs-vicky-wasik-d07c5480d72e49cc85689c1d6d88495e.jpg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://images.unsplash.com/photo-1616645258469-ec681c17f3ee?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bHVuY2glMjBmb29kfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&w=1000&q=80',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: 'https://feelgoodfoodie.net/wp-content/uploads/2020/02/Date-Shake-4.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://media.istockphoto.com/photos/breakfast-served-with-coffee-juice-egg-and-rolls-picture-id625232510?k=20&m=625232510&s=612x612&w=0&h=SLtKH7uPgTx9iTlhSre-V-RhEGtQjgE3T7kZI2qfZGw=',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://media.self.com/photos/5a3bc75ee1ef6d3e6b880568/1:1/w_1002,h_1002,c_limit/high-protein-lunch-challenge.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfl0ZR8eG3co_H-vlD064rs22skiHdcrikv3_Wcc4S_xkTdo2mshiVVyWSNK-wKcMGNYI&usqp=CAU',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://www.eatthis.com/wp-content/uploads/sites/4/2021/03/woman-eating-oatmeal-breakfast.jpg?quality=82&strip=1&resize=640%2C360',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://www.realmomnutrition.com/wp-content/uploads/Pizza-Bagel.jpeg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: 'https://media.istockphoto.com/photos/chocolate-milk-and-whipped-cream-picture-id926990564?k=20&m=926990564&s=612x612&w=0&h=maw0rkzBpzhLIBasS3FPWJG2kENlOTcyYSVV5zHdAME=',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default data;